backend:
  name: github
  repo: randomtruffles/domi.link
  branch: master
  site_domain: xenodochial-carson-f04c57.netlify.com

media_folder: "images/shortlinks"

collections:
  - name: "shortlinks" # Used in routes, e.g., /admin/collections/blog
    label: "Shortlinks" # Used in the UI
    folder: "/" # The path to the folder where the documents are stored
    filter: {field: "layout", value: "redirect"}
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    delete: true
    fields: # The fields for each document, usually in front matter
      - {label: "Custom shortlink",  name: "title", hint: "Example: Entering 'blitz' will create the domi.link at domi.link/blitz. You cannot change this once published, just create a new one with the changed name.", widget: "string"}
      - {label: "Owner", name: "owner", hint: "Eg. truffles - This is just for bookkeeping!", widget: "string"}
      - {label: "Layout", name: "layout", default: "redirect", widget: "hidden"}
      - {label: "Redirect", name: "redirect", hint: "What the custom shortlink should redirect to. You can edit this at any time.", widget:"string"}
  - name: "assemble_me" # Used in routes, e.g., /admin/collections/blog
    label: "assemble_me's shortlinks" # Used in the UI
    folder: "/" # The path to the folder where the documents are stored
    filter: {field: "owner", value: "assemble_me"}
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    delete: true
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Custom shortlink",  name: "title", hint: "Example: Entering 'blitz' will create the domi.link at domi.link/blitz. You cannot change this once published, just create a new one with the changed name.", widget: "string"}
      - {label: "Owner", name: "owner", default: "assemble_me", widget: "hidden"}
      - {label: "Layout", name: "layout", default: "redirect", widget: "hidden"}
      - {label: "Redirect", name: "redirect", hint: "What the custom shortlink should redirect to. You can edit and change this at any time.", widget:"string"}
  - name: "Mic Qsenoch" # Used in routes, e.g., /admin/collections/blog
    label: "Mic Qsenoch's shortlinks" # Used in the UI
    folder: "/" # The path to the folder where the documents are stored
    filter: {field: "owner", value: "Mic Qsenoch"}
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    delete: true
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Custom shortlink",  name: "title", hint: "Example: Entering 'blitz' will create the domi.link at domi.link/blitz. You cannot change this once published, just create a new one with the changed name.", widget: "string"}
      - {label: "Owner", name: "owner", default: "Mic Qsenoch", widget: "hidden"}
      - {label: "Layout", name: "layout", default: "redirect", widget: "hidden"}
      - {label: "Redirect", name: "redirect", hint: "What the custom shortlink should redirect to. You can edit and change this at any time.", widget:"string"}
  - name: "muenstercheese" # Used in routes, e.g., /admin/collections/blog
    label: "muenstercheese's shortlinks" # Used in the UI
    folder: "/" # The path to the folder where the documents are stored
    filter: {field: "owner", value: "muenstercheese"}
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    delete: true
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Custom shortlink",  name: "title", hint: "Example: Entering 'blitz' will create the domi.link at domi.link/blitz. You cannot change this once published, just create a new one with the changed name.", widget: "string"}
      - {label: "Owner", name: "owner", default: "muenstercheese", widget: "hidden"}
      - {label: "Layout", name: "layout", default: "redirect", widget: "hidden"}
      - {label: "Redirect", name: "redirect", hint: "What the custom shortlink should redirect to. You can edit and change this at any time.", widget:"string"}
  - name: "RozyRoz" # Used in routes, e.g., /admin/collections/blog
    label: "RozyRoz's shortlinks" # Used in the UI
    folder: "/" # The path to the folder where the documents are stored
    filter: {field: "owner", value: "RozyRoz"}
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Custom shortlink",  name: "title", hint: "Example: Entering 'blitz' will create the domi.link at domi.link/blitz - Note: Once you publish it, editing will not change the shortlink. You must delete the existing shortlink and create a new shortlink.", widget: "string"}
      - {label: "Owner", name: "owner", default: "RozyRoz", widget: "hidden"}
      - {label: "Layout", name: "layout", default: "redirect", widget: "hidden"}
      - {label: "Redirect", name: "redirect", hint: "What the custom shortlink should redirect to. You can edit this at any time.", widget:"string"}
  - name: "tracer" # Used in routes, e.g., /admin/collections/blog
    label: "tracer's shortlinks" # Used in the UI
    folder: "/" # The path to the folder where the documents are stored
    filter: {field: "owner", value: "tracer"}
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    delete: true
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Custom shortlink",  name: "title", hint: "Example: Entering 'blitz' will create the domi.link at domi.link/blitz. You cannot change this once published, just create a new one with the changed name.", widget: "string"}
      - {label: "Owner", name: "owner", default: "tracer", widget: "hidden"}
      - {label: "Layout", name: "layout", default: "redirect", widget: "hidden"}
      - {label: "Redirect", name: "redirect", hint: "What the custom shortlink should redirect to. You can edit this at any time.", widget:"string"}
  - name: "truffles" # Used in routes, e.g., /admin/collections/blog
    label: "truffles's shortlinks" # Used in the UI
    folder: "/" # The path to the folder where the documents are stored
    filter: {field: "owner", value: "truffles"}
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    delete: true
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Custom shortlink",  name: "title", hint: "Example: Entering 'blitz' will create the domi.link at domi.link/blitz. You cannot change this once published, just create a new one with the changed name.", widget: "string"}
      - {label: "Owner", name: "owner", default: "truffles", widget: "hidden"}
      - {label: "Layout", name: "layout", default: "redirect", widget: "hidden"}
      - {label: "Redirect", name: "redirect", hint: "What the custom shortlink should redirect to. You can edit this at any time.", widget:"string"}
  - name: "championship" # Used in routes, e.g., /admin/collections/blog
    label: "championship's shortlinks" # Used in the UI
    folder: "/" # The path to the folder where the documents are stored
    filter: {field: "owner", value: "championship"}
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    delete: true
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Custom shortlink",  name: "title", hint: "Example: Entering 'blitz' will create the domi.link at domi.link/blitz. You cannot change this once published, just create a new one with the changed name.", widget: "string"}
      - {label: "Owner", name: "owner", default: "championship", widget: "hidden"}
      - {label: "Layout", name: "layout", default: "redirect", widget: "hidden"}
      - {label: "Redirect", name: "redirect", hint: "What the custom shortlink should redirect to. You can edit and change this at any time.", widget:"string"}
